//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  ...tanstackConfig,
  {
    rules: {
      'import/no-cycle': 'off',
      'import/order': 'off',
      'sort-imports': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/require-await': 'off',
      'pnpm/json-enforce-catalog': 'off',
    },
  },
  {
    // Generated artefacts — not authored, regenerated by `tsr generate` /
    // `convex dev`, and already carry their own eslint-disable banner.
    ignores: [
      'eslint.config.js',
      'prettier.config.js',
      'convex/_generated/**',
      'app/routeTree.gen.ts',
      '.output/**',
      '.nitro/**',
      'dist/**',
      'coverage/**',
    ],
  },
]
