import { useState } from 'react'
import { useMutation } from 'convex/react'
// api.d.ts types are regenerated by `npx convex dev`; cast until then
// eslint-disable-next-line @typescript-eslint/no-explicit-any
import { api } from '../../convex/_generated/api'
import type { SelectedGeometry } from './RouteMap'

const _api = api as any // eslint-disable-line @typescript-eslint/no-explicit-any

interface Props {
  geometry: SelectedGeometry | null
}

export function SaveRouteButton({ geometry }: Props) {
  const save = useMutation(_api.routes.save)
  const [status, setStatus] = useState<'idle' | 'saving' | 'done' | 'error'>('idle')
  const [shareId, setShareId] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  const [errorMsg, setErrorMsg] = useState<string | null>(null)

  const shareUrl = shareId
    ? `${typeof window !== 'undefined' ? window.location.origin : ''}/r/${shareId}`
    : null

  async function handleSave() {
    if (!geometry) return
    setStatus('saving')
    setErrorMsg(null)
    try {
      const result = await save({
        start: geometry.start,
        end: geometry.end,
        path: geometry.path,
        distanceMeters: geometry.distanceMeters,
      })
      setShareId((result as { shareId: string }).shareId)
      setStatus('done')
    } catch (e) {
      setErrorMsg(e instanceof Error ? e.message : 'Erreur lors de la sauvegarde')
      setStatus('error')
    }
  }

  async function handleCopy() {
    if (!shareUrl) return
    await navigator.clipboard.writeText(shareUrl)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const disabled = !geometry || status === 'saving'

  return (
    <div className="flex flex-col gap-2">
      <button
        onClick={handleSave}
        disabled={disabled}
        className="flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"
      >
        {status === 'saving' ? (
          <>
            <span className="inline-block h-3 w-3 animate-spin rounded-full border-2 border-white border-t-transparent" />
            Sauvegarde…
          </>
        ) : (
          'Sauvegarder la route'
        )}
      </button>

      {status === 'error' && errorMsg && (
        <p className="text-xs text-red-600">{errorMsg}</p>
      )}

      {status === 'done' && shareUrl && (
        <div className="rounded-lg border border-green-200 bg-green-50 p-3 text-sm">
          <p className="mb-2 font-medium text-green-800">Route sauvegardée !</p>
          <div className="flex items-center gap-2">
            <a
              href={shareUrl}
              target="_blank"
              rel="noreferrer"
              className="flex-1 truncate rounded border border-green-300 bg-white px-2 py-1 text-xs text-blue-600 hover:underline"
            >
              {shareUrl}
            </a>
            <button
              onClick={handleCopy}
              className="shrink-0 rounded bg-green-600 px-2 py-1 text-xs text-white hover:bg-green-700"
            >
              {copied ? 'Copié !' : 'Copier'}
            </button>
          </div>
          <button
            onClick={() => setStatus('idle')}
            className="mt-2 text-xs text-green-600 hover:underline"
          >
            Fermer
          </button>
        </div>
      )}
    </div>
  )
}

export default SaveRouteButton
