/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as MesRoutesRouteImport } from './routes/mes-routes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RouteNewRouteImport } from './routes/route.new'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const MesRoutesRoute = MesRoutesRouteImport.update({
  id: '/mes-routes',
  path: '/mes-routes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteNewRoute = RouteNewRouteImport.update({
  id: '/route/new',
  path: '/route/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compte': typeof CompteRoute
  '/login': typeof LoginRoute
  '/mes-routes': typeof MesRoutesRoute
  '/tos': typeof TosRoute
  '/route/new': typeof RouteNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compte': typeof CompteRoute
  '/login': typeof LoginRoute
  '/mes-routes': typeof MesRoutesRoute
  '/tos': typeof TosRoute
  '/route/new': typeof RouteNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compte': typeof CompteRoute
  '/login': typeof LoginRoute
  '/mes-routes': typeof MesRoutesRoute
  '/tos': typeof TosRoute
  '/route/new': typeof RouteNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compte' | '/login' | '/mes-routes' | '/tos' | '/route/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compte' | '/login' | '/mes-routes' | '/tos' | '/route/new'
  id:
    | '__root__'
    | '/'
    | '/compte'
    | '/login'
    | '/mes-routes'
    | '/tos'
    | '/route/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompteRoute: typeof CompteRoute
  LoginRoute: typeof LoginRoute
  MesRoutesRoute: typeof MesRoutesRoute
  TosRoute: typeof TosRoute
  RouteNewRoute: typeof RouteNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-routes': {
      id: '/mes-routes'
      path: '/mes-routes'
      fullPath: '/mes-routes'
      preLoaderRoute: typeof MesRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route/new': {
      id: '/route/new'
      path: '/route/new'
      fullPath: '/route/new'
      preLoaderRoute: typeof RouteNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompteRoute: CompteRoute,
  LoginRoute: LoginRoute,
  MesRoutesRoute: MesRoutesRoute,
  TosRoute: TosRoute,
  RouteNewRoute: RouteNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
